version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 7
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 1000
  method-complexity:
    enabled: true
    config:
      threshold: 15
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 10 #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: 10 #language-specific defaults. overrides affect all languages.
plugins:
  sonar-python:
    enabled: true
  bandit:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true

exclude_patterns: 
- "wafo/tests/"
- "wafo/MSPPT.py"
- "wafo/MSO.py"